travis:
  secure:
    BINSTAR_TOKEN: mVqC2hhJ/q8B9ceWinr2+ZGOOSWONPWenlkQpkngJwmqPZspeVEl8IL0JUnBwPt7JRsGBCmEh8t1XNCSXsbY5vcKZiEZPh7i9qIEh1ELSo81Hy2xPRTjgYFgphSsTmdTpvwJNwdFfaUItukLcXJWFPGAza800frf1Sjfj9aNHtM1NixH5Z/JsvF/qBkaMKolDV+E57LYtgpjRVA3ABQZMz+H6fqfHK0L3LJpjmv/sgU9YptcTGOTYtmAqNLRIUqDOOsjsnQbSCeN8q1RnMsfoIrtBth20/2EKO/fgGY0re+KIku5cixQceY/sT3EP8LaLrOHwFGJH7C1yoaYX7Xbrb78MQDGNagWXCCLD0G7r+llC1ZKp2V9Us5urX/dJXW4V7On/597SGCU57+OvT9PTNIP/KgJbCXsDwxZqG1pmqe7ZArFbM/wsi4z4RqkXCEK8kHtUV1RISlRZ7/4pIsWFs53EGa7BYaW9AMlMY6SS2aD3RB9wLcRqY9tU1O7FFcYZUEmrNK0zWk3nyU5ASLLwHdnHdGcb64Wz4mLf/gAlJlHvaAs9c8Yn/ys8JFXMZipP1oqDSPhif//s1jVUEENpBg+e1V74GVGh0jK0dYYyVMe6509joOMnF0f8mt8yaHQGCK0ErBFntQq5FUe6steqUlV06TsBkMmUriU4yJnaC8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
